- name: Install required system packages
  apt:
    name: ['curl', 'git', 'python3-pip', 'software-properties-common']
    state: present
    update_cache: yes

- name: Install Docker
  shell: |
    curl -fsSL https://get.docker.com | sh
    usermod -aG docker ubuntu
  args:
    executable: /bin/bash

- name: Install Docker Compose
  pip:
    name: docker-compose
