- name: Deploy Application with Traefik
  hosts: app_server
  become: true
  tasks:
    - name: Update and upgrade system packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required dependencies
      apt:
        name:
          - git
          - docker.io
          - docker-compose
        state: present

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Clone the application repository
      git:
        repo: "https://github.com/DanielAzeez/DevOps-Stage-4.git"
        dest: "/opt/app"
        version: main
        force: yes

    - name: Bring up the entire application stack
      command:
        cmd: docker-compose -f /opt/app/docker-compose.yml up -d
